//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentEvent
    {
        public CurrentEvent()
        {
            this.Attendees = new HashSet<Attendee>();
        }
    
        public int ID { get; set; }
        public string summary { get; set; }
        public Nullable<System.DateTime> schedule { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual ICollection<Attendee> Attendees { get; set; }
    }
}
